iter/map_test.go, iter/zip_test.go
Added a couple of example tests.
=> Add example tests

.github/PULL_REQUEST_TEMPLATE/pull_request.md
This PR introduces this very pull request template to help reduce back-and-forth between contributors and maintainers.
#20
=> Add pull request template

iter/filter.go, iter/filter_test.go
Adds `FilterMap` function and `FilterMapIter` type to iter package.
=> Implement `FilterMap` iterator

.github/workflows/test.yaml
Ensure go-functional works on Go 1.19 and get ahead of any changes needed.
=> Test on Go 1.19 release candidate

.github/workflows/test.yaml
=> Upgrade Go to 1.19 in CI

README.md
Add report card to badges
https://github.com/BooleanCat/go-functional/issues/47
=> Add report card to badges

result/result.go, result/result_test.go
=> Add UnwrapErr to Result

internal/gen/methodset/methodset.go, internal/gen/methodset/methodset_test.go
Add helper type for generator script that's coming shortly.
None.
=> Experiment: Add helper type for generator

README.md, iter/chain.go, iter/chain_test.go, iter/channel.go, iter/channel_test.go, iter/counter.go, iter/counter_test.go, iter/cycle.go, iter/cycle_test.go, iter/drop.go, iter/drop_test.go, iter/exhausted.go, iter/exhausted_test.go, iter/filter.go, iter/filter_test.go, iter/iter_test.go, iter/lift.go, iter/lift_test.go, iter/lines.go, iter/lines_test.go, iter/map.go, iter/map_test.go, iter/repeat.go, iter/repeat_test.go, iter/take.go, iter/take_test.go, iter/zip.go, iter/zip_test.go
Allow chaining of .Take.
https://github.com/BooleanCat/go-functional/issues/55
=> Allow chaining of .Take

.github/workflows/test.yaml, Makefile, v2/go.mod, v2/iter/iter.go, v2/iter/iter_test.go
Create a stub directory for building v2 using rangefunc to check that CI works as expected.
N/A.
=> Test v2 in CI as it's being developed

.github/workflows/test.yaml, v2/iter/iter_test.go
=> Set up go workspaces in CI for testing v2

constraints/constraints.go, iter/filters/filters.go
Ordered is in the standard library, no need to redefine it.
N/A.
None.
=> Remove redundant constraint type

iter/map_test.go
Due to a change in how pull iterators are implemented, coverage dropped on these tests.
This just includes coverage for map.
N/A
=> increase map test coverage

.github/workflows/test.yaml
Upgrade Go in CI to 1.23rc2
None.
N/A.
=> Upgrade Go in CI to 1.23rc2

README.md
Document remaining consumers
None.
=> Document remaining consumers

.prettierrc, README.md
Use prettier to format Markdown
None
=> Use prettier to format Markdown

README.md, it/drop.go, it/drop_test.go, it/itx/drop.go, it/itx/drop_test.go, it/itx/take.go, it/itx/take_test.go, it/take.go, it/take_test.go
Behaves in the same way as you'd expect from Python's itertools.
Request on the Go Slack.
None.
=> Add TakeWhile and DropWhile family of iterators

it/filter/filter.go, it/filter/filter_test.go
Support filtering using regex matching.
None.
None.
=> Support regexp match filtering

README.md, it/iter.go, it/iter_test.go, it/itx/iter.go, it/itx/iter_test.go
Add Drain consumer to exhaust an iterator and drop all values.
None.
None.
=> Add Drain consumer

README.md, it/iter.go, it/iter_test.go
Add All and Any consumers that behave as they do in Python.
None.
None.
=> Add All and Any consumers

.github/workflows/test.yaml
Get ahead of the 1.24 release by testing with it now.
None.
None.
=> Test with 1.24.0-rc.1

.github/workflows/test.yaml
=> Test with Go 1.25
