BooleanCat/go-functional

README.md

Core concepts for Iterators are communicated in the main README leaving all other docs to the reference docs (which will be overhauled separately.

Rewrite README as a brief overview

---

iter/iter.go
iter/iter_test.go

Hi! I've impelmented fold as described [here](https://github.com/BooleanCat/go-functional/issues/7)
I've made the function argument to be the last, so it's more convenient to pass inline functions

Implement iter.Fold

---

iter/ops/binary.go
iter/ops/binary_test.go
iter/ops/unary.go
iter/ops/unary_test.go

Add some functions that performs built-in binary operators
Resolves #22
- NOTE: [580efcf](https://github.com/BooleanCat/go-functional/pull/30/commits/580efcf89bb57f85f83b703506c103eb7d087579) adds multiple trivial functions. It might violate "single change". I will split commit if you want.
I split `ops.go` into `unary.go` and `binary.go`.
I'll revert it or split it under another rule.
I haven't renamed `Add` by `Sum` as suggested in #22 .
I have a justification for it: `sum(x) = fold(x, 0, +)` and `add(x, y) = x + y` rather than `sum(x, y) = x + y)`
Regardless the reason above, I'm OK to rename it if you want.
`Product` vs `Multiply` is same …

Add some functions that performs built-in binary operators

---

iter/channel.go
iter/channel_test.go

Add FromChannel iterator.
An iterator that plugs consumes a channel. The iterator is exhausted when the channel is closed.
[issue #29](https://github.com/BooleanCat/go-functional/issues/29)

Channel iterator

---

option/option.go
option/option_test.go

Adds `Map` high order function, closes #33 
#33 

Add `Map` to option package

---

.github/workflows/test.yaml
iter/find.go

Go 1.21 has shipped, test with that and stop testing end-of-life versions.
None

Test in CI with latest Go version

---

option/json_test.go

Added explicit test to force an error when unmarshaling JSON through the Option struct.  
It isn't related to an issue, simply a chore to increase coverage on the option/json.go file where reasonably practicable.
I'm a hobby developer so please have some patience if I've missed something.

Added additional JSON test

---

.github/workflows/test.yaml
.gitignore
Makefile

Show code coverage when PRs are opened.
N/A.

Add code coverage to PRs and commits

---

iter/zip_test.go

Improve test coverage in zip.go
N/A

Improve test coverage in zip.go

---

README.md
iter/lift_test.go

Improve test coverage in lift.go
N/A.

Improve test coverage in lift.go

---

iter/iter.go
iter/iter_test.go

A sentence or two is fine, the rest should be clear from the code change and related issue.
It adds for each for iterator package, which can execute a callback on each item contained by an iterator.
Please provide a link to the issue that this change resolved.
#45 
If there is no such issue, consider creating one first. Discussions concerning proposed changes ought to take place in an issue and not in pull requests. Pull requests not associated with an issue are less likely to be merged and more likely to ask for changes.

Add iter.ForEach

---

iter/filter.go
iter/filter_test.go
iter/lift.go

Ensure FilterMap returns a concrete type. It erroneously returns an interface at the moment.
None.

Ensure FilterMap returns a concrete type

---

README.md
iter/chain.go
iter/chain_test.go
iter/channel.go
iter/channel_test.go
iter/drop.go
iter/drop_test.go
iter/exhausted.go
iter/exhausted_test.go
iter/filter.go
iter/filter_test.go
iter/lift.go
iter/lift_test.go
iter/lines.go
iter/lines_test.go
iter/map.go
iter/map_test.go
iter/take.go
iter/take_test.go
iter/zip.go
iter/zip_test.go

Allow iterator collection from method call for more terse code.
https://github.com/BooleanCat/go-functional/issues/55

Add collect method to each iter (except Count)

---

README.md
iter/chain.go
iter/chain_test.go
iter/channel.go
iter/channel_test.go
iter/counter.go
iter/counter_test.go
iter/cycle.go
iter/cycle_test.go
iter/drop.go
iter/drop_test.go
iter/exhausted.go
iter/exhausted_test.go
iter/filter.go
iter/filter_test.go
iter/lift.go
iter/lift_test.go
iter/lines.go
iter/lines_test.go
iter/map.go
iter/map_test.go
iter/repeat.go
iter/repeat_test.go
iter/take.go
iter/take_test.go
iter/zip.go
iter/zip_test.go

Support chaining the Drop iterator on other iterators.
https://github.com/BooleanCat/go-functional/issues/55

Support chaining Drop

---

internal/gen/directive/directive.go
internal/gen/directive/directive_test.go

In order to generate chainable methods, we need a parser for generator directives. This is that.
None.

Experiment: Add parser for generator directives

---

internal/gen/directive/directive.go
internal/gen/directive/directive_test.go

Support more complicated types for directives. While building the code generator for method chaining I noticed the existing directives didn't support types like `Tuple[T, U]`.
None.

Experiment: Support more complicated types for directives

---

iter/chain.go
iter/chain_test.go
iter/channel.go
iter/channel_test.go
iter/counter.go
iter/counter_test.go
iter/cycle.go
iter/cycle_test.go
iter/drop.go
iter/drop_test.go
iter/exhausted.go
iter/exhausted_test.go
iter/filter.go
iter/filter_test.go
iter/iter_test.go
iter/lift.go
iter/lift_test.go
iter/lines.go
iter/lines_test.go
iter/map.go
iter/map_test.go
iter/repeat.go
iter/repeat_test.go
iter/take.go
iter/take_test.go
iter/zip.go
iter/zip_test.go

Add .ForEach for iterator method chaining
https://github.com/BooleanCat/go-functional/issues/55

Add .ForEach for iterator method chaining

---

README.md
iter/iter.go
iter/iter_test.go

- Add BaseIteratorFilter method to iter.go
- Update Filter examples on README.md to use new syntax
#59 

Refactor filter

---

.golangci.yml

**Description of the change.**
Added configurations to setup `golangci-lint`.
following command will run all the linter
```
make lint
```
Example of lint error
```
iter/chain.go:13:43: `colour` is a misspelling of `color` (misspell)
// iterators to exhaustion first to last. colour
^
make: *** [lint] Error 1
```
Resolves : https://github.com/BooleanCat/go-functional/issues/77

feat: added golangci-lint config

---

result/json.go
result/json_test.go
result/result.go
result/result_test.go

Add the `Unmarshal` method to the **Result** struct.
https://github.com/BooleanCat/go-functional/issues/79
None

Add Result.Unmarshal unmarshaling method

---

iter/enumerate_test.go
iter/zip.go
iter/zip_test.go

Added stringer implementation for `iter.Pair[T, U]`
Example
```golang
pair1 := iter.Pair[string, interface{}]{One: "1", Two:"2"}
fmt.Printf("%s\n", foo)
```
Output
```
(1,2)
```
https://github.com/BooleanCat/go-functional/issues/82

feat: add stringer implementation for `iter.Pair[T, U]`

---

iter/counter.go
iter/counter_test.go

This PR addresses `fmt.Stringer` implementation for `iter.CountIter`, in other PRs I'll address the `fmt.Stringer` for other iterators.
https://github.com/BooleanCat/go-functional/issues/81

feat: Add Stringer interface impl for iter.CountIter

---

iter/chain.go
iter/chain_test.go
iter/counter.go
iter/map.go
iter/map_test.go

Support Stringer representation for `ChainIter` and `MapIter`. This PR is a demonstration of the general pattern of string representations for Iterators that yield generic values (unlike `Counter` that always yields an `int`).
#81 

Support Stringer for ChainIter and MapIter

---

.github/workflows/test.yaml

Actions is spitting out warnings about caching not working because there's no `go.sum` file. This makes sense because there are no dependencies. To remove this noisy warning caching is disabled.
None.

Disable caching in Go action in CI

---

.github/workflows/test.yaml

In order to head up any compatibility issues with Go 1.22, start testing with the release candidate.
N/A.

Test with go1.22 release candidate in CI

---

future/maps/maps.go
future/maps/maps_test.go
future/slices/slices.go
future/slices/slices_test.go
internal/assert/assert.go
iter/count.go
iter/count_test.go
iter/drop.go
iter/drop_test.go
iter/enumerate.go
iter/enumerate_test.go
iter/filter.go
iter/filter/filter.go
iter/filter/filter_test.go
iter/filter_test.go
iter/iter.go
iter/iter_test.go
iter/map.go
iter/map_test.go
iter/op/op_test.go
iter/take.go
iter/take_test.go
iter/zip.go
iter/zip_test.go

- All iterators now natively return and use the `Seq` types rather than this projects type alias, favouring compatibility with the standard library over convenience features like chaining.
- Added iterators for the Seq2 variants of existing iterators
- Renamed `Lift` to `Values` and moved to future shadow package `slices` (to be deleted when Go 1.23 is released)
- Renamed `LiftHashMap` to `All` and moved to future shadow package `maps` (to be deleted when Go 1.23 is released)
None.
There are breaking changes here.

Adapt project to current 1.23 iter API

---

iter/channel.go
iter/channel_test.go

Allow for a channel to be created from an `iter.Seq` and vice versa.
None.

Support To/FromChannel

---

Makefile
iter/take_test.go

Using the builtin slices and maps packages instead of the recently deleted future package has lowered coverage, this improves it.
N/A

Improve test coverage

---

iter/channel_test.go
iter/cycle_test.go
iter/drop_test.go
iter/zip_test.go

Due to a change in how pull iterators are implemented, coverage dropped on these tests.
Closes #115 
N/A

increase test coverage for channel, cycle, drop & zip

---

it/iter.go
it/iter_test.go

Add consumers to find the minimum and maximum values from iterators.
#120 

Add Max and Min consumers

---

it/itx/chain_test.go
it/itx/channel_test.go
it/itx/cycle_test.go
it/itx/drop_test.go
it/itx/enumerate_test.go
it/itx/filter_test.go
it/itx/iter.go
it/itx/iter_test.go
it/itx/take_test.go
it/itx/zip_test.go

Using `itx.From(slices.Values(slice))` will be a fairly common pattern so this is to make that a bit less verbose with `itx.FromSlice(slice)` (and same for `FromMap`).
None.
N/A.

Support FromSlice and FromMap helpers in itx

---

it/iter.go
it/iter_test.go
it/itx/iter.go
it/itx/iter_test.go
it/lines_test.go

A common form of iteratoring with an `iter.Seq` will be pairs of values where the right side is an error (for exampling iterating over lines in an `io.Reader`. `CollectErr` is a helper that will collect the left values from the iterator and the right `error` values will be joined into a single error.
None.
~~I've also added some helper functions to extend the power of this change. `op.Apply{Left/Right}` are to be used with `Map2` in order to apply a function to only left or right values. I'm considering `Filter{Left/Right}` also.~~

Add CollectErr consumer and related helpers

---

it/itx/map.go
it/itx/map_test.go
it/map.go

Transform is a limited form of Map where the argument type is the same as the return type, allowing it to be chained.
Add `Transform` iter to `itx`.
`Transform` is a limited form of `Map` where the argument type is the same as the return type, allowing it to be chained.
N/A.
N/A.

Add Transform iter to itx

---

it/enumerate_test.go
it/exhausted_test.go
it/iter.go
it/iter_test.go
it/itx/iter.go
it/itx/iter_test.go

This is a breaking change.
Add `TryCollect` to collect an `iter.Seq2[V any, error]` into a `[]V` and an `error`. Iteration terminate at the first error.
Remove `CollectErr` and replace with the more general `Collect2`.
None.

Add TryCollect and Collect2 consumers and remove CollectErr

---

README.md
it/iter.go
it/iter_test.go
it/itx/integers.go
it/itx/iter.go
it/itx/iter_test.go
it/op/op_test.go

Much improved docs for READ, well at least the beginnings of it. Will follow up with more changes to add more missing docs.
None.
Within this change are a few others mixed in, my bad!
1. I removed `TryCollect` from `itx` for consistency.
2. I renamed `Reduce` to `Fold`. I'll later add a `Fold` variant called `Reduce` that uses the first item yielded as the initial value (just like Rust)

Significantly improve docs in README (partial)

---

README.md
it/filter.go
it/filter_test.go
it/itx/filter.go
it/itx/filter_test.go

Allow for filtering iterators where the predicate can return an error.
#135 

Add FilterError iterator

---

README.md
it/itx/map.go
it/itx/map_test.go
it/map.go
it/map_test.go

Support map operations that can return an error.
N/A.

Add MapError iterator

---

.github/workflows/test.yaml

Go 1.23 is GA so stop testing with the release candidate.
N/A.
None.

Test in CI with go 1.23

---

README.md
it/iter.go
it/iter_test.go

Contains consumer will return true or false depending on whether the iterator yields the provided value.
None.
None.

Add Contains consumer

---

README.md
it/iter.go
it/iter_test.go

Add MustCollect consumer that behaves like TryCollect except that it panics when an error is encountered.
None.
None.

Add MustCollect consumer

---

README.md
it/compact.go
it/compact_test.go

The Compact iterator will remove zero values from the iterator.
None.
N/A.

Add Compact iterator

---

it/filter_unique.go
it/filter_unique_test.go

Address the issue raised in #146 
Adds a Filter unique functionality to only yield unique values. 

Add filter unique functionality

---

it/op/op.go
it/op/op_test.go

Other packages commonly use pointers as optionals for values. These helpers can help to manage those values cleanly with `it.Map`.
None.
None.

Provide ref and deref ops for Map

---

README.md

The documentation for `All` in the README was wrong - the correct return value is `false`.
n/a
n/a

fix documentation for `All`, which actually returns false

---

.github/workflows/test.yaml
.golangci.yml

Use and support the latest version of `golangci-lint`. The configuration file was migrated used `golangci-lint migrate`.
None.
N/A.

Use golangci-lint v2
